system {
    host-name R1;
    root-authentication {
        plain-text-password-value "Poclab123!";
    }
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 1.1.1.1/32;
            }
            family mpls;
        }
    }
    eth1 {
        description "to R2";
        unit 0 {
            family inet {
                address 10.0.12.1/30;
            }
            family mpls;
        }
    }
    eth2 {
        description "to R3";
        unit 0 {
            family inet {
                address 10.0.13.1/30;
            }
            family mpls;
        }
    }
    eth3 {
        description "to R11 (VRF VPN1)";
        unit 0 {
            family inet {
                address 10.1.11.1/30;
            }
        }
    }
}
routing-instances {
    VPN1 {
        instance-type vrf;
        interface eth3.0;
        route-distinguisher 65000:1;
        vrf-target target:65000:1;
        protocols {
            bgp {
                group CE-R11 {
                    type external;
                    peer-as 65011;
                    neighbor 10.1.11.2;
                }
            }
        }
    }
}
protocols {
    mpls {
        interface eth1.0;
        interface eth2.0;
        interface lo0.0;
    }
    ospf {
        traffic-engineering;
        area 0.0.0.0 {
            interface lo0.0 {
                passive;
            }
            interface eth1.0;
            interface eth2.0;
        }
    }
    ldp {
        interface eth1.0;
        interface eth2.0;
        interface lo0.0;
    }
    bgp {
        group IBGP-PE {
            type internal;
            local-address 1.1.1.1;
            family inet-vpn {
                unicast;
            }
            neighbor 2.2.2.2;
            neighbor 3.3.3.3;
        }
    }
}
routing-options {
    router-id 1.1.1.1;
    autonomous-system 65000;
}
