system {
    host-name R11;
    root-authentication {
        plain-text-password-value "Poclab123!";
    }
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 11.11.11.11/32;
            }
        }
    }
    eth1 {
        description "to R1 (PE)";
        unit 0 {
            family inet {
                address 10.1.11.2/30;
            }
        }
    }
    eth2 {
        description "to R2 (PE)";
        unit 0 {
            family inet {
                address 10.2.11.2/30;
            }
        }
    }
}
policy-options {
    policy-statement EXPORT-LO {
        term loopback {
            from {
                protocol direct;
                interface lo0.0;
            }
            then accept;
        }
        term reject-all {
            then reject;
        }
    }
}
protocols {
    bgp {
        group PE-R1 {
            type external;
            peer-as 65000;
            neighbor 10.1.11.1 {
                export EXPORT-LO;
            }
        }
        group PE-R2 {
            type external;
            peer-as 65000;
            neighbor 10.2.11.1 {
                export EXPORT-LO;
            }
        }
    }
}
routing-options {
    router-id 11.11.11.11;
    autonomous-system 65011;
}
