system {
    host-name R12;
    root-authentication {
        plain-text-password-value "Poclab123!";
    }
}
interfaces {
    lo0 {
        unit 0 {
            family inet {
                address 12.12.12.12/32;
            }
        }
    }
    eth1 {
        description "to R3 (PE)";
        unit 0 {
            family inet {
                address 10.0.312.2/30;
            }
        }
    }
}
policy-options {
    policy-statement EXPORT-LO {
        term loopback {
            from {
                protocol direct;
                interface lo0.0;
            }
            then accept;
        }
        term reject-all {
            then reject;
        }
    }
}
protocols {
    bgp {
        group PE-R3 {
            type external;
            peer-as 65000;
            neighbor 10.0.312.1 {
                export EXPORT-LO;
            }
        }
    }
}
routing-options {
    router-id 12.12.12.12;
    autonomous-system 65012;
}
